#!/usr/bin/env bash
set -eu

## for now USED only for CLI

source $PWD/scripts/_common_.sh


_reload_env
cli_build() {
  deps=(go node npm)
  _check_dependencies ${deps[@]}
  local bin_name="$BIN_NAME"
  # @todo make it dynamic
  local arch="arm64"
  mkdir -p target/macos/bin

  local out_path=${PREFIX:-$HOME/.local/bin/$bin_name}
  _log_debug "Building \`${bin_name}\` binary for $arch to \`$out_path\`"
  npm --progress false install --prefix internal/web > /dev/null 2>&1

  local build_cmd="go build -o $PWD/target/macos/bin/$bin_name"
  # Build frontend

  export CGO_ENABLED=1 && GOARCH=$arch
  if [[ "${WATCH_FILES+x}" ]];then
    go run build/main.go &
    local command=${command:-help}
    local arg=t${arg:-''}
    local flag=${flag:-''}
     _log_debug "Running WATCH mode for: \`${command} ${arg} ${flag}\`"
    build_cmd="CompileDaemon -include=\"*.html\" -exclude-dir=\"${PWD}/internal/web/node_modules\" -directory=\"${PWD}\" -build=\"${build_cmd}\" -command=\"$bin_name $command $flag $arg\" -graceful-kill=true -log-prefix=false -color=true"
  else
    go run build/main.go > /dev/null 2>&1
  fi

  eval $build_cmd
  # ls -la $out_path
  local alias_cmd="ln -sfn ${PWD}/target/macos/bin/${bin_name} ${out_path}"
  _log_info "Creating symlink at:" $out_path
  exec $alias_cmd

}

BUILD=${BUILD:-cli}

shift

USAGE="Usage: Build usage todo ....."

while getopts 'c:a:f:' OPTION; do
  case "$OPTION" in
    c)
      command="$OPTARG"
      ;;
    a)
      arg="$OPTARG"
      ;;
    f)
      flag=$OPTARG
      ;;
    \? ) echo $USAGE
         exit 1;;
    * ) echo $usage
        exit 1;;
  esac

done
shift "$(($OPTIND -1))"

# Let's see what it is to build
case "$BUILD" in
  cli)
    cli_build
    ;;
  \? ) echo $USAGE
      exit 1;;
  * ) echo $usage
      exit 1;;
esac